### ISSUE TITLE
How to change listening port in nameko?

### ISSUE THREAD

**Issue by laike9m** [onefinestay/nameko#364]
I want to start an HTTP service but not on port 8000, how do I do this? Can't find any information in doc.

**Comment by mattbennett** [comment]
You need to use a config file with the key `WEB_SERVER_ADDRESS`:

``` yaml
# config.yaml
AMQP_URI: amqp://guest:guest@localhost
WEB_SERVER_ADDRESS: 0.0.0.0:8888
```

``` shell
nameko run --config config.yaml your_service_module
```

**Comment by laike9m** [comment]
Thx matt. It would save people a lot of time if this is written in doc.

**Comment by davidszotten** [comment]
pull requests to the docs are most welcome

**Comment by frisellcpl** [comment]
Follow up question on this topic. The port used by the connection to rabbitmq (not the port used by rabbitmq itself). Can that somehow be specified?

**Comment by mattbennett** [comment]
There are two config variables related to the RabbitMQ broker. One specifying the AMQP connection, and other specifying the address of the Management interface.

``` yml
# config.yaml
AMQP_URI: amqp://guest:guest@localhost:5672/vhost
RABBIT_CTL_URI: http://guest:guest@localhost:15672
```

Does that answer your question?
